### ISSUE TITLE
Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#38]
```
events.js:72
    throw er; // Unhandled 'error' event
          ^
TypeError: Invalid non-string/buffer chunk
at chunkInvalid (_stream_readable.js:384:10)
at readableAddChunk (_stream_readable.js:138:12)
at Connection.Readable.push (_stream_readable.js:128:10)
at Connection._read (/usr/local/cozy/apps/thelounge/node_modules/thelounge/node_modules/irc-framework/src/connection.js:209:33)
at Connection.pushCommandBuffer (/usr/local/cozy/apps/thelounge/node_modules/thelounge/node_modules/irc-framework/src/connection.js:219:14)
at processIrcLines (/usr/local/cozy/apps/thelounge/node_modules/thelounge/node_modules/irc-framework/src/connection.js:428:17)
at Connection.socketOnData (/usr/local/cozy/apps/thelounge/node_modules/thelounge/node_modules/irc-framework/src/connection.js:393:5)
at CleartextStream.socketReadableCb (/usr/local/cozy/apps/thelounge/node_modules/thelounge/node_modules/irc-framework/src/connection.js:135:34)
at CleartextStream.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:427:10)
```

Appears to happen on node 0.10.

**Comment by prawnsalad** [comment]
We have decided to only support node 4+, making this error now redundant.
