### ISSUE TITLE
Double `whois`ing nick in succession errors

### ISSUE THREAD

**Issue by MaxLeiter** [kiwiirc/irc-framework#88]
```
 /root/lounge/node_modules/irc-framework/src/commands/handlers/user.js:89
            cache.nick = nick;
                         ^


ReferenceError: nick is not defined
    at IrcCommandHandler.RPL_ENDOFWHOIS (/root/lounge/node_modules/irc-framework/src/commands/handlers/user.js:89:26)
    at IrcCommandHandler.executeCommand (/root/lounge/node_modules/irc-framework/src/commands/handler.js:62:37)
    at IrcCommandHandler.dispatch (/root/lounge/node_modules/irc-framework/src/commands/handler.js:49:14)
    at /root/lounge/node_modules/irc-framework/src/client.js:103:36
    at next (/root/lounge/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/root/lounge/node_modules/middleware-handler/index.js:64:3)
    at Connection.<anonymous> (/root/lounge/node_modules/irc-framework/src/client.js:97:31)
    at Connection.emit (/root/lounge/node_modules/eventemitter3/index.js:130:35)
    at Connection.processReadBuffer (/root/lounge/node_modules/irc-framework/src/connection.js:265:14)
    at Connection.socketLine (/root/lounge/node_modules/irc-framework/src/connection.js:99:14)
```

**Comment by prawnsalad** [comment]
That was fixed here https://github.com/kiwiirc/irc-framework/commit/a3b6b74885cd90ca8d98cf58e533bfb694da2441

You need to update your irc-framework

**Comment by MaxLeiter** [comment]
On 2.6.1...
